CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- TABLAS BASE
-- ==========================================

CREATE TABLE roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR NOT NULL
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  rol_id INTEGER NOT NULL REFERENCES roles(id),

  nombres VARCHAR NOT NULL,
  apellidos VARCHAR NOT NULL,

  dni VARCHAR UNIQUE NOT NULL,
  correo VARCHAR UNIQUE NOT NULL,

  telefono VARCHAR,

  password_hash VARCHAR NOT NULL,

  estado VARCHAR DEFAULT 'activo',

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- PERFILES ACADÉMICOS
-- ==========================================

CREATE TABLE estudiantes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id UUID REFERENCES users(id),

  codigo_estudiante VARCHAR UNIQUE NOT NULL,

  fecha_nacimiento DATE,
  direccion VARCHAR,

  estado VARCHAR DEFAULT 'activo',

  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE docentes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id UUID REFERENCES users(id),

  especialidad VARCHAR,

  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE apoderados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id UUID REFERENCES users(id),

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- RELACIÓN APODERADO ↔ ESTUDIANTE
-- ==========================================

CREATE TABLE estudiante_apoderado (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  estudiante_id INTEGER REFERENCES estudiantes(id),
  apoderado_id INTEGER REFERENCES apoderados(id),

  parentesco VARCHAR NOT NULL,

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- ESTRUCTURA ACADÉMICA
-- ==========================================

CREATE TABLE grados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  nombre VARCHAR NOT NULL
);

CREATE TABLE secciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  nombre VARCHAR NOT NULL
);

CREATE TABLE aulas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  grado_id INTEGER REFERENCES grados(id),
  seccion_id INTEGER REFERENCES secciones(id),

  turno VARCHAR NOT NULL,

  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE periodos_academicos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  nombre VARCHAR NOT NULL,

  fecha_inicio DATE,
  fecha_fin DATE,

  estado VARCHAR DEFAULT 'activo',

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- MATRÍCULA Y DOCUMENTOS
-- ==========================================

CREATE TABLE matriculas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  estudiante_id INTEGER REFERENCES estudiantes(id),
  aula_id INTEGER REFERENCES aulas(id),
  periodo_id INTEGER REFERENCES periodos_academicos(id),

  estado VARCHAR DEFAULT 'pendiente',

  fecha DATE,

  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE documentos_matricula (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  matricula_id INTEGER REFERENCES matriculas(id),

  nombre_archivo VARCHAR NOT NULL,
  url_archivo VARCHAR NOT NULL,

  estado VARCHAR DEFAULT 'pendiente',

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- CURSOS Y ASIGNACIONES
-- ==========================================

CREATE TABLE cursos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  nombre VARCHAR NOT NULL
);

CREATE TABLE docente_curso (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  docente_id INTEGER REFERENCES docentes(id),
  curso_id INTEGER REFERENCES cursos(id),
  aula_id INTEGER REFERENCES aulas(id),

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- HORARIOS
-- ==========================================

CREATE TABLE horarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  aula_id INTEGER REFERENCES aulas(id),
  curso_id INTEGER REFERENCES cursos(id),
  docente_id INTEGER REFERENCES docentes(id),

  dia_semana VARCHAR NOT NULL,

  hora_inicio TIME,
  hora_fin TIME,

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- ASISTENCIAS
-- ==========================================

CREATE TABLE asistencias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  estudiante_id INTEGER REFERENCES estudiantes(id),
  horario_id INTEGER REFERENCES horarios(id),

  fecha DATE NOT NULL,

  estado VARCHAR NOT NULL,

  observacion TEXT,

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- NOTAS
-- ==========================================

CREATE TABLE notas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  estudiante_id INTEGER REFERENCES estudiantes(id),
  curso_id INTEGER REFERENCES cursos(id),
  aula_id INTEGER REFERENCES aulas(id),

  bimestre VARCHAR NOT NULL,

  nota NUMERIC(5,2),

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- REFORZAMIENTOS
-- ==========================================

CREATE TABLE reforzamientos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  estudiante_id INTEGER REFERENCES estudiantes(id),
  curso_id INTEGER REFERENCES cursos(id),
  docente_id INTEGER REFERENCES docentes(id),

  fecha DATE,

  hora_inicio TIME,
  hora_fin TIME,

  observacion TEXT,

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- COMUNICADOS
-- ==========================================

CREATE TABLE comunicados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  titulo VARCHAR NOT NULL,

  contenido TEXT NOT NULL,

  publicado_por UUID REFERENCES users(id),

  fecha TIMESTAMP DEFAULT now(),

  created_at TIMESTAMP DEFAULT now()
);

-- ==========================================
-- NOTIFICACIONES
-- ==========================================

CREATE TABLE notificaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id UUID REFERENCES users(id),

  tipo VARCHAR NOT NULL,

  mensaje TEXT NOT NULL,

  estado VARCHAR DEFAULT 'pendiente',

  fecha TIMESTAMP DEFAULT now(),

  created_at TIMESTAMP DEFAULT now()
);